package com.example.projectNC.domain;


public enum YearOfStudying {
    FIRST_YEAR_FIRST_SEMESTER;
 /*   FIRST_YEAR_SECOND_SEMESTER,
    SECOND_YEAR_FIRST_SEMESTER,
    SECOND_YEAR_SECOND_SEMESTER,
    THIRD_YEAR_FIRST_SEMESTER,
    THIRD_YEAR_SECOND_SEMESTER,
    FORTH_YEAR_FIRST_SEMESTER,
    FORTH_YEAR_SECOND_SEMESTER,
    FIFTH_YEAR_FIRST_SEMESTER,
    FIFTH_YEAR_SECOND_SEMESTER,
    SIXTH_YEAR_FIRST_SEMESTER,
    SIXTH_YEAR_SECOND_SEMESTER,

  */
}